// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6rJZiNRwSCruf1YOLVYKgcwelnbRNArs',
    appId: '1:426241944264:web:69f4ec9216f1f19e2993fd',
    messagingSenderId: '426241944264',
    projectId: 'picstate-859a6',
    authDomain: 'picstate-859a6.firebaseapp.com',
    databaseURL: 'https://picstate-859a6-default-rtdb.firebaseio.com',
    storageBucket: 'picstate-859a6.appspot.com',
    measurementId: 'G-VF85G3G5P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeKvQJFdilTwFbsFwSCPGlEWD1cpbRCjY',
    appId: '1:426241944264:android:70993934965c45542993fd',
    messagingSenderId: '426241944264',
    projectId: 'picstate-859a6',
    databaseURL: 'https://picstate-859a6-default-rtdb.firebaseio.com',
    storageBucket: 'picstate-859a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHzNYuD5LrXUMNd0aYgFXLnHF3q6jyALY',
    appId: '1:426241944264:ios:1159d4c8985572d42993fd',
    messagingSenderId: '426241944264',
    projectId: 'picstate-859a6',
    databaseURL: 'https://picstate-859a6-default-rtdb.firebaseio.com',
    storageBucket: 'picstate-859a6.appspot.com',
    iosClientId: '426241944264-ascpgv6evkb0cvhit8kjd3rvjuk19jhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.picstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHzNYuD5LrXUMNd0aYgFXLnHF3q6jyALY',
    appId: '1:426241944264:ios:1159d4c8985572d42993fd',
    messagingSenderId: '426241944264',
    projectId: 'picstate-859a6',
    databaseURL: 'https://picstate-859a6-default-rtdb.firebaseio.com',
    storageBucket: 'picstate-859a6.appspot.com',
    iosClientId: '426241944264-ascpgv6evkb0cvhit8kjd3rvjuk19jhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.picstate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6rJZiNRwSCruf1YOLVYKgcwelnbRNArs',
    appId: '1:426241944264:web:945670fa2493dcf12993fd',
    messagingSenderId: '426241944264',
    projectId: 'picstate-859a6',
    authDomain: 'picstate-859a6.firebaseapp.com',
    databaseURL: 'https://picstate-859a6-default-rtdb.firebaseio.com',
    storageBucket: 'picstate-859a6.appspot.com',
    measurementId: 'G-0D3SPMH7G1',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC6rJZiNRwSCruf1YOLVYKgcwelnbRNArs',
    appId: '1:426241944264:web:318fec2c60c690922993fd',
    messagingSenderId: '426241944264',
    projectId: 'picstate-859a6',
    authDomain: 'picstate-859a6.firebaseapp.com',
    databaseURL: 'https://picstate-859a6-default-rtdb.firebaseio.com',
    storageBucket: 'picstate-859a6.appspot.com',
    measurementId: 'G-4XQYJS64WZ',
  );
}
